data = {
    "Difficile":[
        {
            "question":"Quelle est la caractéristiques à ne pas négliger pour ne pas se faire mal au dos ?",
            "reponse":["TAILLE"],
            "texte":"Dans le cadre d’un achat d’aspirateur, il est très important de choisir un appareil offrant de bonnes caractéristiques, en plus d’une utilisation pratique. En effet, s’occuper des tâches ménagères ne représente pas forcément un plaisir alors autant les réaliser dans de bonnes conditions !\\n\\n\n" +
                "Côté pratique, assurez-vous avant votre achat que l’aspirateur de votre choix propose des commandes faciles d’accès, que ce soit via une poignée ou au pied. Si vous en avez également la possibilité, favorisez un appareil équipé d’un manche télescopique, ceci afin d’avoir un équipement à votre taille... idéal pour ne pas se faire mal au dos.\\n\\n\n" +
                "D’autres éléments pratiques concernent quant à eux la longueur du fil ainsi que l’enrouleur. Selon la taille de votre habitation, il peut être judicieux de privilégier un appareil équipé d’unlong fil, ceci afin de vous éviter de débrancher/rebrancher votre appareil plusieurs fois au cours de la même séance de tâches ménagères. Pour ce qui est de l’enrouleur, c’est un petit plus non négligeable qui permet de ranger le fil en toute simplicité.\\n\\n\n" +
                "Côté maniabilité, assurez-vous que l’appareil sera agréable à utiliser et facile à déplacer à travers les pièces de votre appartement ou maison. En vue de favoriser cet aspect, privilégiez un appareil léger car il pourrait vous arriver de le porter pour monter des marches d’escalier ou encore pour aspirer en hauteur ; privilégiez également un équipement doté de roues multidirectionnelles. Votre aspirateur vous suivra ainsi en toute simplicité, sans que vous ayez besoin de vous en soucier.\\n\\n\n" +
                "Concernant le rangement, les aspirateurs balais, robot et à main sont pratiques car ils ne demandent pas beaucoup de place pour être rangés. Fonction très pratique, la position parking permet de ranger votre aspirateur traîneau en position verticale, ce qui offre un gain de place non négligeable dans un placard.\\n\\n\n"
        },
        {
            "question":"De quoi va dépendre la longueur de fil de votre aspirateur ?",
            "reponse":["TAILLE", "HABITATION"],
            "texte":"Dans le cadre d’un achat d’aspirateur, il est très important de choisir un appareil offrant de bonnes caractéristiques, en plus d’une utilisation pratique. En effet, s’occuper des tâches ménagères ne représente pas forcément un plaisir alors autant les réaliser dans de bonnes conditions !\\n\\n\n" +
                "Côté pratique, assurez-vous avant votre achat que l’aspirateur de votre choix propose des commandes faciles d’accès, que ce soit via une poignée ou au pied. Si vous en avez également la possibilité, favorisez un appareil équipé d’un manche télescopique, ceci afin d’avoir un équipement à votre taille... idéal pour ne pas se faire mal au dos.\\n\\n\n" +
                "D’autres éléments pratiques concernent quant à eux la longueur du fil ainsi que l’enrouleur. Selon la taille de votre habitation, il peut être judicieux de privilégier un appareil équipé d’unlong fil, ceci afin de vous éviter de débrancher/rebrancher votre appareil plusieurs fois au cours de la même séance de tâches ménagères. Pour ce qui est de l’enrouleur, c’est un petit plus non négligeable qui permet de ranger le fil en toute simplicité.\\n\\n\n" +
                "Côté maniabilité, assurez-vous que l’appareil sera agréable à utiliser et facile à déplacer à travers les pièces de votre appartement ou maison. En vue de favoriser cet aspect, privilégiez un appareil léger car il pourrait vous arriver de le porter pour monter des marches d’escalier ou encore pour aspirer en hauteur ; privilégiez également un équipement doté de roues multidirectionnelles. Votre aspirateur vous suivra ainsi en toute simplicité, sans que vous ayez besoin de vous en soucier.\\n\\n\n" +
                "Concernant le rangement, les aspirateurs balais, robot et à main sont pratiques car ils ne demandent pas beaucoup de place pour être rangés. Fonction très pratique, la position parking permet de ranger votre aspirateur traîneau en position verticale, ce qui offre un gain de place non négligeable dans un placard.\\n\\n\n"
        },
        {
            "question":"Quel petit plus permet de ranger le fil en toute simplicité ? ",
            "reponse":["ENROULEUR"],
            "texte":"Dans le cadre d’un achat d’aspirateur, il est très important de choisir un appareil offrant de bonnes caractéristiques, en plus d’une utilisation pratique. En effet, s’occuper des tâches ménagères ne représente pas forcément un plaisir alors autant les réaliser dans de bonnes conditions !\\n\\n\n" +
                "Côté pratique, assurez-vous avant votre achat que l’aspirateur de votre choix propose des commandes faciles d’accès, que ce soit via une poignée ou au pied. Si vous en avez également la possibilité, favorisez un appareil équipé d’un manche télescopique, ceci afin d’avoir un équipement à votre taille... idéal pour ne pas se faire mal au dos.\\n\\n\n" +
                "D’autres éléments pratiques concernent quant à eux la longueur du fil ainsi que l’enrouleur. Selon la taille de votre habitation, il peut être judicieux de privilégier un appareil équipé d’unlong fil, ceci afin de vous éviter de débrancher/rebrancher votre appareil plusieurs fois au cours de la même séance de tâches ménagères. Pour ce qui est de l’enrouleur, c’est un petit plus non négligeable qui permet de ranger le fil en toute simplicité.\\n\\n\n" +
                "Côté maniabilité, assurez-vous que l’appareil sera agréable à utiliser et facile à déplacer à travers les pièces de votre appartement ou maison. En vue de favoriser cet aspect, privilégiez un appareil léger car il pourrait vous arriver de le porter pour monter des marches d’escalier ou encore pour aspirer en hauteur ; privilégiez également un équipement doté de roues multidirectionnelles. Votre aspirateur vous suivra ainsi en toute simplicité, sans que vous ayez besoin de vous en soucier.\\n\\n\n" +
                "Concernant le rangement, les aspirateurs balais, robot et à main sont pratiques car ils ne demandent pas beaucoup de place pour être rangés. Fonction très pratique, la position parking permet de ranger votre aspirateur traîneau en position verticale, ce qui offre un gain de place non négligeable dans un placard.\\n\\n\n"
        },
        {
            "question":"Quels sont les deux critères qui facilitent l’utilisation d’un aspirateur ? ",
            "reponse":["APPAREIL", "LEGER", "ROUES", "MULTIDIRECTIONNELLE"],
            "texte":"Dans le cadre d’un achat d’aspirateur, il est très important de choisir un appareil offrant de bonnes caractéristiques, en plus d’une utilisation pratique. En effet, s’occuper des tâches ménagères ne représente pas forcément un plaisir alors autant les réaliser dans de bonnes conditions !\\n\\n\n" +
                "Côté pratique, assurez-vous avant votre achat que l’aspirateur de votre choix propose des commandes faciles d’accès, que ce soit via une poignée ou au pied. Si vous en avez également la possibilité, favorisez un appareil équipé d’un manche télescopique, ceci afin d’avoir un équipement à votre taille... idéal pour ne pas se faire mal au dos.\\n\\n\n" +
                "D’autres éléments pratiques concernent quant à eux la longueur du fil ainsi que l’enrouleur. Selon la taille de votre habitation, il peut être judicieux de privilégier un appareil équipé d’unlong fil, ceci afin de vous éviter de débrancher/rebrancher votre appareil plusieurs fois au cours de la même séance de tâches ménagères. Pour ce qui est de l’enrouleur, c’est un petit plus non négligeable qui permet de ranger le fil en toute simplicité.\\n\\n\n" +
                "Côté maniabilité, assurez-vous que l’appareil sera agréable à utiliser et facile à déplacer à travers les pièces de votre appartement ou maison. En vue de favoriser cet aspect, privilégiez un appareil léger car il pourrait vous arriver de le porter pour monter des marches d’escalier ou encore pour aspirer en hauteur ; privilégiez également un équipement doté de roues multidirectionnelles. Votre aspirateur vous suivra ainsi en toute simplicité, sans que vous ayez besoin de vous en soucier.\\n\\n\n" +
                "Concernant le rangement, les aspirateurs balais, robot et à main sont pratiques car ils ne demandent pas beaucoup de place pour être rangés. Fonction très pratique, la position parking permet de ranger votre aspirateur traîneau en position verticale, ce qui offre un gain de place non négligeable dans un placard.\\n\\n\n"
        },
        {
            "question":"Les trois types d’aspirateurs les plus faciles à ranger ? ",
            "reponse":["BALAIS", "ROBOT", "MAIN"],
            "texte":"Dans le cadre d’un achat d’aspirateur, il est très important de choisir un appareil offrant de bonnes caractéristiques, en plus d’une utilisation pratique. En effet, s’occuper des tâches ménagères ne représente pas forcément un plaisir alors autant les réaliser dans de bonnes conditions !\\n\\n\n" +
                "Côté pratique, assurez-vous avant votre achat que l’aspirateur de votre choix propose des commandes faciles d’accès, que ce soit via une poignée ou au pied. Si vous en avez également la possibilité, favorisez un appareil équipé d’un manche télescopique, ceci afin d’avoir un équipement à votre taille... idéal pour ne pas se faire mal au dos.\\n\\n\n" +
                "D’autres éléments pratiques concernent quant à eux la longueur du fil ainsi que l’enrouleur. Selon la taille de votre habitation, il peut être judicieux de privilégier un appareil équipé d’unlong fil, ceci afin de vous éviter de débrancher/rebrancher votre appareil plusieurs fois au cours de la même séance de tâches ménagères. Pour ce qui est de l’enrouleur, c’est un petit plus non négligeable qui permet de ranger le fil en toute simplicité.\\n\\n\n" +
                "Côté maniabilité, assurez-vous que l’appareil sera agréable à utiliser et facile à déplacer à travers les pièces de votre appartement ou maison. En vue de favoriser cet aspect, privilégiez un appareil léger car il pourrait vous arriver de le porter pour monter des marches d’escalier ou encore pour aspirer en hauteur ; privilégiez également un équipement doté de roues multidirectionnelles. Votre aspirateur vous suivra ainsi en toute simplicité, sans que vous ayez besoin de vous en soucier.\\n\\n\n" +
                "Concernant le rangement, les aspirateurs balais, robot et à main sont pratiques car ils ne demandent pas beaucoup de place pour être rangés. Fonction très pratique, la position parking permet de ranger votre aspirateur traîneau en position verticale, ce qui offre un gain de place non négligeable dans un placard.\\n\\n\n"
        }
    ]
}
